/**
 * Menu Descriptions
 * Detailed descriptions, tooltips, and metadata for all menu items
 */

export interface MenuDescription {
  menuId: string;
  itemId: string;
  label: string;
  tooltip: string;
  description: string;
  category: string;
  helpUrl?: string;
  relatedItems?: string[];
}

export const MENU_DESCRIPTIONS: Record<string, MenuDescription> = {
  // FILE MENU
  file_new: {
    menuId: 'file',
    itemId: 'file_new',
    label: 'New Blueprint',
    tooltip: 'Create a new blank blueprint',
    description: 'Creates a new empty blueprint. You can choose a template or start from scratch.',
    category: 'Basic Operations',
    helpUrl: 'docs/getting-started#new-blueprint',
    relatedItems: ['file_open', 'file_save'],
  },
  file_open: {
    menuId: 'file',
    itemId: 'file_open',
    label: 'Open Blueprint',
    tooltip: 'Open an existing blueprint from disk (Ctrl+O)',
    description: 'Open a blueprint file from your computer. Supports .bp, .json, and other formats.',
    category: 'Basic Operations',
    helpUrl: 'docs/file-operations#open',
    relatedItems: ['file_open_recent', 'file_import'],
  },
  file_open_recent: {
    menuId: 'file',
    itemId: 'file_open_recent',
    label: 'Open Recent',
    tooltip: 'Access recently opened blueprints',
    description: 'Quick access to your recently opened blueprints. List updates automatically.',
    category: 'Basic Operations',
    helpUrl: 'docs/file-operations#recent',
    relatedItems: ['file_open', 'file_clear_recent'],
  },
  file_save: {
    menuId: 'file',
    itemId: 'file_save',
    label: 'Save',
    tooltip: 'Save current blueprint to disk (Ctrl+S)',
    description: 'Saves the current blueprint to its file location. Auto-save runs every 30 seconds.',
    category: 'Save Operations',
    helpUrl: 'docs/file-operations#save',
    relatedItems: ['file_save_as', 'file_save_all'],
  },
  file_save_as: {
    menuId: 'file',
    itemId: 'file_save_as',
    label: 'Save As',
    tooltip: 'Save blueprint with new name/location (Ctrl+Shift+S)',
    description: 'Save the current blueprint with a new name or to a different location.',
    category: 'Save Operations',
    helpUrl: 'docs/file-operations#save-as',
    relatedItems: ['file_save', 'file_save_all'],
  },
  file_save_all: {
    menuId: 'file',
    itemId: 'file_save_all',
    label: 'Save All',
    tooltip: 'Save all open blueprints (Ctrl+Alt+S)',
    description: 'Saves all currently open blueprints. Useful when working with multiple files.',
    category: 'Save Operations',
    helpUrl: 'docs/file-operations#save-all',
    relatedItems: ['file_save', 'file_save_as'],
  },
  file_import: {
    menuId: 'file',
    itemId: 'file_import',
    label: 'Import',
    tooltip: 'Import blueprint from various sources',
    description: 'Import blueprints from JSON, files, URLs, or cloud storage.',
    category: 'Import/Export',
    helpUrl: 'docs/import-export#import',
    relatedItems: ['file_export', 'file_import_json'],
  },
  file_import_json: {
    menuId: 'file',
    itemId: 'file_import_json',
    label: 'Import from JSON',
    tooltip: 'Load blueprint from JSON file',
    description: 'Load a blueprint that was previously exported as JSON. Preserves all data.',
    category: 'Import/Export',
    helpUrl: 'docs/import-export#json',
    relatedItems: ['file_export_json'],
  },
  file_import_file: {
    menuId: 'file',
    itemId: 'file_import_file',
    label: 'Import from File',
    tooltip: 'Browse and select blueprint file',
    description: 'Open file browser to select and import a blueprint file (.bp, .json, .yaml).',
    category: 'Import/Export',
    helpUrl: 'docs/import-export#file',
  },
  file_import_url: {
    menuId: 'file',
    itemId: 'file_import_url',
    label: 'Import from URL',
    tooltip: 'Import blueprint from remote URL',
    description: 'Download and import a blueprint from a URL. Useful for sharing blueprints online.',
    category: 'Import/Export',
    helpUrl: 'docs/import-export#url',
  },
  file_import_cloud: {
    menuId: 'file',
    itemId: 'file_import_cloud',
    label: 'Import from Cloud',
    tooltip: 'Import from cloud storage provider',
    description: 'Import blueprints from connected cloud storage (Google Drive, Dropbox, etc.).',
    category: 'Import/Export',
    helpUrl: 'docs/import-export#cloud',
  },
  file_export: {
    menuId: 'file',
    itemId: 'file_export',
    label: 'Export',
    tooltip: 'Export blueprint to various formats (Ctrl+E)',
    description: 'Export blueprint in multiple formats for sharing, documentation, or code generation.',
    category: 'Import/Export',
    helpUrl: 'docs/import-export#export',
    relatedItems: ['file_import', 'file_export_json'],
  },
  file_export_json: {
    menuId: 'file',
    itemId: 'file_export_json',
    label: 'Export as JSON',
    tooltip: 'Save blueprint in JSON format',
    description: 'Export blueprint as JSON for version control, sharing, or backup.',
    category: 'Import/Export',
    helpUrl: 'docs/export#json',
    relatedItems: ['file_import_json'],
  },
  file_export_code: {
    menuId: 'file',
    itemId: 'file_export_code',
    label: 'Generate Code',
    tooltip: 'Generate source code from blueprint',
    description: 'Generate C++, Python, JavaScript, or other source code from the blueprint.',
    category: 'Import/Export',
    helpUrl: 'docs/export#code-generation',
  },
  file_export_image: {
    menuId: 'file',
    itemId: 'file_export_image',
    label: 'Export as Image',
    tooltip: 'Save blueprint visualization as image',
    description: 'Export blueprint diagram as PNG, SVG, or other image format for documentation.',
    category: 'Import/Export',
    helpUrl: 'docs/export#image',
  },
  file_export_pdf: {
    menuId: 'file',
    itemId: 'file_export_pdf',
    label: 'Export as PDF',
    tooltip: 'Create PDF documentation of blueprint',
    description: 'Generate a professional PDF document with blueprint diagram and documentation.',
    category: 'Import/Export',
    helpUrl: 'docs/export#pdf',
  },
  file_print: {
    menuId: 'file',
    itemId: 'file_print',
    label: 'Print',
    tooltip: 'Print blueprint to printer or PDF (Ctrl+P)',
    description: 'Print the blueprint to a physical printer or save as PDF.',
    category: 'File Management',
    helpUrl: 'docs/file-operations#print',
  },
  file_close: {
    menuId: 'file',
    itemId: 'file_close',
    label: 'Close',
    tooltip: 'Close current blueprint (Ctrl+W)',
    description: 'Close the current blueprint. You will be prompted to save if changes exist.',
    category: 'File Management',
    helpUrl: 'docs/file-operations#close',
  },
  file_exit: {
    menuId: 'file',
    itemId: 'file_exit',
    label: 'Exit',
    tooltip: 'Exit application (Alt+F4)',
    description: 'Close the application. All unsaved blueprints will be saved to auto-save.',
    category: 'File Management',
    helpUrl: 'docs/file-operations#exit',
  },

  // EDIT MENU
  edit_undo: {
    menuId: 'edit',
    itemId: 'edit_undo',
    label: 'Undo',
    tooltip: 'Undo the last action (Ctrl+Z)',
    description: 'Reverse the last action. You can undo up to 50 actions.',
    category: 'Undo/Redo',
    helpUrl: 'docs/editing#undo',
    relatedItems: ['edit_redo'],
  },
  edit_redo: {
    menuId: 'edit',
    itemId: 'edit_redo',
    label: 'Redo',
    tooltip: 'Redo the last undone action (Ctrl+Y)',
    description: 'Repeat the last undone action. Useful after undo.',
    category: 'Undo/Redo',
    helpUrl: 'docs/editing#redo',
    relatedItems: ['edit_undo'],
  },
  edit_cut: {
    menuId: 'edit',
    itemId: 'edit_cut',
    label: 'Cut',
    tooltip: 'Cut selected items (Ctrl+X)',
    description: 'Cut selected nodes and connections. Can be pasted elsewhere.',
    category: 'Clipboard Operations',
    helpUrl: 'docs/editing#cut',
    relatedItems: ['edit_copy', 'edit_paste'],
  },
  edit_copy: {
    menuId: 'edit',
    itemId: 'edit_copy',
    label: 'Copy',
    tooltip: 'Copy selected items (Ctrl+C)',
    description: 'Copy selected nodes and connections to clipboard.',
    category: 'Clipboard Operations',
    helpUrl: 'docs/editing#copy',
    relatedItems: ['edit_cut', 'edit_paste'],
  },
  edit_paste: {
    menuId: 'edit',
    itemId: 'edit_paste',
    label: 'Paste',
    tooltip: 'Paste copied items (Ctrl+V)',
    description: 'Paste copied items from clipboard. Creates copies of cut items.',
    category: 'Clipboard Operations',
    helpUrl: 'docs/editing#paste',
    relatedItems: ['edit_copy', 'edit_cut'],
  },
  edit_duplicate: {
    menuId: 'edit',
    itemId: 'edit_duplicate',
    label: 'Duplicate',
    tooltip: 'Create copy of selected node(s) (Ctrl+D)',
    description: 'Create an exact copy of selected nodes at a slightly offset position.',
    category: 'Node Operations',
    helpUrl: 'docs/editing#duplicate',
    relatedItems: ['edit_copy', 'edit_delete'],
  },
  edit_delete: {
    menuId: 'edit',
    itemId: 'edit_delete',
    label: 'Delete',
    tooltip: 'Remove selected item(s) (Delete)',
    description: 'Delete selected nodes and their connections. This action can be undone.',
    category: 'Node Operations',
    helpUrl: 'docs/editing#delete',
    relatedItems: ['edit_undo'],
  },
  edit_select_all: {
    menuId: 'edit',
    itemId: 'edit_select_all',
    label: 'Select All',
    tooltip: 'Select all nodes on canvas (Ctrl+A)',
    description: 'Select all nodes and connections on the current canvas.',
    category: 'Selection',
    helpUrl: 'docs/editing#select-all',
    relatedItems: ['edit_deselect_all'],
  },
  edit_deselect_all: {
    menuId: 'edit',
    itemId: 'edit_deselect_all',
    label: 'Deselect All',
    tooltip: 'Deselect all nodes (Ctrl+Shift+A)',
    description: 'Clear current selection. Useful to deselect everything quickly.',
    category: 'Selection',
    helpUrl: 'docs/editing#deselect',
    relatedItems: ['edit_select_all'],
  },
  edit_find: {
    menuId: 'edit',
    itemId: 'edit_find',
    label: 'Find',
    tooltip: 'Search for nodes/connections (Ctrl+F)',
    description: 'Search the blueprint for nodes by name, type, or properties.',
    category: 'Search & Replace',
    helpUrl: 'docs/editing#find',
    relatedItems: ['edit_replace'],
  },
  edit_replace: {
    menuId: 'edit',
    itemId: 'edit_replace',
    label: 'Find & Replace',
    tooltip: 'Find and replace names (Ctrl+H)',
    description: 'Find and replace node names, variable names, or property values across blueprint.',
    category: 'Search & Replace',
    helpUrl: 'docs/editing#find-replace',
    relatedItems: ['edit_find'],
  },

  // VIEW MENU
  view_zoom_in: {
    menuId: 'view',
    itemId: 'view_zoom_in',
    label: 'Zoom In',
    tooltip: 'Increase canvas zoom level (Ctrl++)',
    description: 'Zoom in to see more detail. Maximum zoom is 400%.',
    category: 'Zoom Controls',
    helpUrl: 'docs/view#zoom',
  },
  view_zoom_out: {
    menuId: 'view',
    itemId: 'view_zoom_out',
    label: 'Zoom Out',
    tooltip: 'Decrease canvas zoom level (Ctrl+-)',
    description: 'Zoom out to see more nodes. Minimum zoom is 10%.',
    category: 'Zoom Controls',
    helpUrl: 'docs/view#zoom',
  },
  view_zoom_fit: {
    menuId: 'view',
    itemId: 'view_zoom_fit',
    label: 'Zoom to Fit',
    tooltip: 'Fit all nodes in viewport (Ctrl+0)',
    description: 'Automatically zoom and pan to fit all nodes in the current view.',
    category: 'Zoom Controls',
    helpUrl: 'docs/view#zoom-fit',
  },
  view_zoom_100: {
    menuId: 'view',
    itemId: 'view_zoom_100',
    label: 'Reset Zoom',
    tooltip: 'Reset zoom to 100%',
    description: 'Reset zoom level back to default 100% scale.',
    category: 'Zoom Controls',
    helpUrl: 'docs/view#zoom',
  },
  view_toggle_grid: {
    menuId: 'view',
    itemId: 'view_toggle_grid',
    label: 'Show Grid',
    tooltip: 'Toggle grid display (Ctrl+G)',
    description: 'Show or hide the alignment grid. Nodes snap to grid when enabled.',
    category: 'Canvas Display',
    helpUrl: 'docs/view#grid',
  },
  view_toggle_minimap: {
    menuId: 'view',
    itemId: 'view_toggle_minimap',
    label: 'Show Mini Map',
    tooltip: 'Toggle miniature map panel',
    description: 'Show or hide the mini map which displays an overview of all nodes.',
    category: 'Canvas Display',
    helpUrl: 'docs/view#minimap',
  },
  view_toggle_toolbar: {
    menuId: 'view',
    itemId: 'view_toggle_toolbar',
    label: 'Show Toolbar',
    tooltip: 'Toggle toolbar visibility',
    description: 'Show or hide the toolbar with common actions.',
    category: 'Canvas Display',
    helpUrl: 'docs/view#toolbar',
  },
  view_panels: {
    menuId: 'view',
    itemId: 'view_panels',
    label: 'Panels',
    tooltip: 'Manage panel visibility',
    description: 'Control visibility of editor panels (Inspector, Library, Console, etc.).',
    category: 'Panels',
    helpUrl: 'docs/view#panels',
  },
  view_panel_inspector: {
    menuId: 'view',
    itemId: 'view_panel_inspector',
    label: 'Show Inspector',
    tooltip: 'Toggle right inspector panel',
    description: 'Show or hide the right panel with node properties and details.',
    category: 'Panels',
    helpUrl: 'docs/view#inspector',
  },
  view_panel_details: {
    menuId: 'view',
    itemId: 'view_panel_details',
    label: 'Show Details',
    tooltip: 'Show node/variable details panel',
    description: 'Display detailed information about selected nodes and variables.',
    category: 'Panels',
    helpUrl: 'docs/view#details',
  },
  view_panel_library: {
    menuId: 'view',
    itemId: 'view_panel_library',
    label: 'Show Node Library',
    tooltip: 'Toggle left node library panel',
    description: 'Show or hide the left panel with available nodes and categories.',
    category: 'Panels',
    helpUrl: 'docs/view#library',
  },
  view_panel_console: {
    menuId: 'view',
    itemId: 'view_panel_console',
    label: 'Show Console',
    tooltip: 'Display debug console',
    description: 'Show or hide the console for debugging output and logs.',
    category: 'Panels',
    helpUrl: 'docs/view#console',
  },
  view_panel_reset: {
    menuId: 'view',
    itemId: 'view_panel_reset',
    label: 'Reset Layout',
    tooltip: 'Restore default layout',
    description: 'Reset all panel positions and sizes to default configuration.',
    category: 'Panels',
    helpUrl: 'docs/view#layout',
  },
  view_layout: {
    menuId: 'view',
    itemId: 'view_layout',
    label: 'Layout',
    tooltip: 'Choose predefined layouts',
    description: 'Select from preset layout configurations optimized for different workflows.',
    category: 'Layout Presets',
    helpUrl: 'docs/view#layouts',
  },
  view_layout_default: {
    menuId: 'view',
    itemId: 'view_layout_default',
    label: 'Default',
    tooltip: 'Standard three-panel layout',
    description: 'Default layout with left library, center canvas, right inspector.',
    category: 'Layout Presets',
  },
  view_layout_compact: {
    menuId: 'view',
    itemId: 'view_layout_compact',
    label: 'Compact',
    tooltip: 'Minimal panel layout',
    description: 'Minimized panels for maximum canvas space. Panels collapse/expand as needed.',
    category: 'Layout Presets',
  },
  view_layout_wide: {
    menuId: 'view',
    itemId: 'view_layout_wide',
    label: 'Wide',
    tooltip: 'Maximize canvas width',
    description: 'Hide inspector panel to maximize horizontal canvas space.',
    category: 'Layout Presets',
  },
  view_layout_focus: {
    menuId: 'view',
    itemId: 'view_layout_focus',
    label: 'Focus Mode',
    tooltip: 'Full screen canvas',
    description: 'Full screen canvas with all panels hidden but accessible.',
    category: 'Layout Presets',
  },
  view_theme: {
    menuId: 'view',
    itemId: 'view_theme',
    label: 'Theme',
    tooltip: 'Select color theme',
    description: 'Choose between dark, light, or automatic theme.',
    category: 'Theme Management',
    helpUrl: 'docs/view#theme',
  },
  view_theme_dark: {
    menuId: 'view',
    itemId: 'view_theme_dark',
    label: 'Dark',
    tooltip: 'Dark theme',
    description: 'Use dark theme optimized for low-light environments.',
    category: 'Theme Management',
  },
  view_theme_light: {
    menuId: 'view',
    itemId: 'view_theme_light',
    label: 'Light',
    tooltip: 'Light theme',
    description: 'Use light theme optimized for bright environments.',
    category: 'Theme Management',
  },
  view_theme_auto: {
    menuId: 'view',
    itemId: 'view_theme_auto',
    label: 'Auto',
    tooltip: 'Follow system preference',
    description: 'Automatically switch between light and dark based on system settings.',
    category: 'Theme Management',
  },

  // TOOLS MENU
  tools_compile: {
    menuId: 'tools',
    itemId: 'tools_compile',
    label: 'Compile',
    tooltip: 'Compile blueprint',
    description: 'Compile the blueprint in the selected mode (Debug, Release, or Shipping).',
    category: 'Compilation',
    helpUrl: 'docs/compilation#compile',
  },
  tools_compile_debug: {
    menuId: 'tools',
    itemId: 'tools_compile_debug',
    label: 'Compile (Debug)',
    tooltip: 'Compile with debug info (F5)',
    description: 'Compile with debug symbols for easier debugging. Slower execution.',
    category: 'Compilation',
    helpUrl: 'docs/compilation#debug',
  },
  tools_compile_release: {
    menuId: 'tools',
    itemId: 'tools_compile_release',
    label: 'Compile (Release)',
    tooltip: 'Optimized compilation',
    description: 'Compile with optimizations enabled. Faster execution, harder to debug.',
    category: 'Compilation',
    helpUrl: 'docs/compilation#release',
  },
  tools_compile_shipping: {
    menuId: 'tools',
    itemId: 'tools_compile_shipping',
    label: 'Compile (Shipping)',
    tooltip: 'Final production build',
    description: 'Compile for final release. Maximum optimizations, no debugging support.',
    category: 'Compilation',
    helpUrl: 'docs/compilation#shipping',
  },
  tools_validate: {
    menuId: 'tools',
    itemId: 'tools_validate',
    label: 'Validate Blueprint',
    tooltip: 'Validate without compiling',
    description: 'Check blueprint for errors and warnings without compiling.',
    category: 'Compilation',
    helpUrl: 'docs/validation',
  },
  tools_analyze: {
    menuId: 'tools',
    itemId: 'tools_analyze',
    label: 'Analysis',
    tooltip: 'Analyze blueprint',
    description: 'Run various analyses on the blueprint to identify issues and improvements.',
    category: 'Analysis',
    helpUrl: 'docs/analysis',
  },
  tools_analyze_complexity: {
    menuId: 'tools',
    itemId: 'tools_analyze_complexity',
    label: 'Complexity Analysis',
    tooltip: 'Calculate cyclomatic complexity',
    description: 'Analyze blueprint complexity including cyclomatic complexity and nesting.',
    category: 'Analysis',
    helpUrl: 'docs/analysis#complexity',
  },
  tools_analyze_performance: {
    menuId: 'tools',
    itemId: 'tools_analyze_performance',
    label: 'Performance Analysis',
    tooltip: 'Estimate execution time',
    description: 'Estimate execution time and identify performance bottlenecks.',
    category: 'Analysis',
    helpUrl: 'docs/analysis#performance',
  },
  tools_analyze_cycles: {
    menuId: 'tools',
    itemId: 'tools_analyze_cycles',
    label: 'Detect Cycles',
    tooltip: 'Find circular dependencies',
    description: 'Detect and highlight circular dependencies in the blueprint graph.',
    category: 'Analysis',
    helpUrl: 'docs/analysis#cycles',
  },
  tools_analyze_deadcode: {
    menuId: 'tools',
    itemId: 'tools_analyze_deadcode',
    label: 'Find Dead Code',
    tooltip: 'Identify unreachable nodes',
    description: 'Find nodes that are unreachable and can be safely removed.',
    category: 'Analysis',
    helpUrl: 'docs/analysis#deadcode',
  },

  // Help menu items follow similar pattern
  // ... (continuing with remaining descriptions)
};

/**
 * Menu Categories
 */
export const MENU_CATEGORIES = {
  file: {
    name: 'File Menu',
    description: 'File operations, import/export, and application control',
    items: 15,
  },
  edit: {
    name: 'Edit Menu',
    description: 'Undo/redo, clipboard, and selection operations',
    items: 14,
  },
  view: {
    name: 'View Menu',
    description: 'Canvas display, zoom, panels, layout, and theme',
    items: 20,
  },
  tools: {
    name: 'Tools Menu',
    description: 'Compilation, analysis, alignment, and AI assistant',
    items: 25,
  },
  help: {
    name: 'Help Menu',
    description: 'Documentation, tutorials, community, and support',
    items: 30,
  },
};

/**
 * Sub-Menu Tree Structure
 */
export const SUBMENU_TREE = {
  file: {
    import: ['json', 'file', 'url', 'cloud'],
    export: ['json', 'code', 'image', 'pdf'],
    recent: ['blueprint1', 'blueprint2', 'blueprint3', 'clear'],
  },
  edit: {},
  view: {
    panels: ['inspector', 'details', 'library', 'console', 'reset'],
    layout: ['default', 'compact', 'wide', 'focus'],
    theme: ['dark', 'light', 'auto'],
  },
  tools: {
    compile: ['debug', 'release', 'shipping', 'validate'],
    analyze: ['complexity', 'performance', 'cycles', 'deadcode'],
    align: ['left', 'right', 'top', 'bottom', 'centerh', 'centerv', 'distrib_h', 'distrib_v'],
    batch: ['enable', 'disable', 'delete', 'group'],
    ai: ['chat', 'suggest', 'generate', 'optimize'],
  },
  help: {
    documentation: ['getting-started', 'nodes', 'api', 'examples', 'tutorials'],
    topics: ['basics', 'concepts', 'advanced', 'tools', 'troubleshooting'],
    community: ['forum', 'discord', 'github', 'share'],
    support: ['contact', 'report', 'feedback', 'faq'],
    tips: ['daily', 'productivity', 'advanced'],
  },
};
